### ISSUE TITLE
OPEN THREAD: Exercises that need more hints

### ISSUE THREAD

**Issue by carols10cents** [rustlings/rustlings#12]
I'm going to leave this issue open basically forever, please feel free to comment here if there was an exercise that could use more of a hint than what was there (if there were hints).

Please specify which exercise it is you're discussing, and if you have any ideas about what would make for a better hint, please let me know!

**Comment by hwbehrens** [comment]
In errorsn.rs, I found myself getting stuck after the second hint. It wasn't clear to me how to coerce the CreationError into the new Box type. I considered doing an 'impl From' for the CreationError enum, but that didn't seem like what the exercise was expecting, based on this part of the hint:
`rewrap some `try!` return values in a `Result::Ok`!`

Breaking that part out into a new hint, or having some 'try' code in the exercise could be useful. Since this is the first introduction to 'try', and the documentation 'try' examples are less than useful (not its fault, error checking is at the end so it uses a lot of unfamiliar terms/constructs), it was an issue for me.

**Comment by sullyj3** [comment]
+1. I'm up to that exact point, and I just can't seem to get my head around it.

**Comment by carols10cents** [comment]
@hwbehrens @sullyj3 thank you for the awesome feedback! I agree that it's a huge jump from errors1 to errorsn. I just added errors2 and errors3 that are way smaller and focus on just the `try!` macro. I also added some more hints to errorsn, including some links to docs that I think are helpful-- could you take a look when you have a chance and let me know what you think? Thanks!!!
