### ISSUE TITLE
RustBridge Paris feedback

### ISSUE THREAD

**Issue by ashleygwilliams** [rustlings/rustlings#85]
Hey everyone! This is an issue for people to post feedback and ideas they came up with during the exercise session at RustBridge Paris! Post anything you have, be it criticism, ideas, general feedback here!

**Comment by anchnk** [comment]
Example `primitive_types3.rs` points to that part of the documentation https://doc.rust-lang.org/stable/book/second-edition/ch03-02-data-types.html#arrays.

But this portion of the documentation, unless I am wrong, does not indicate how to initialize arrays with a specific length as in `[value; N]`.

**Comment by oe** [comment]
@anchnk So, the specific reason for that is because initializing an Array with a specified length only works when the type of element implements the `Copy` trait, and there's apparently currently a discussion going on about refactoring that part. The link to the docs originally pointed to the first version of the Rust book, which _did_ cover this, but it was taken out for the above reasons. We should probably explain how to initialize an Array in this way ourselves instead of linking to the book for this.
